#!/bin/bash
#

# Bundles v1.0.0
# This script sets defaults.
# www.brianspeir.com
#
# Copyright (C) 2013 Brian Speir. All rights reserved.
#
# Licensed under The BSD 3-Clause License. You may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/BSD-3-Clause


echo ""
echo "Welcome to Bundles."
echo ""
echo "Please quit open apps."
echo ""
echo "To proceed, enter your password, or type Ctrl-C to abort."
echo ""
sudo -v

SOURCE="https://raw.github.com/brianspeir/Bundles/master"

shopt -s nullglob

if [[ -n "$1" ]]; then
    # Argument passed from the command line
    SELECTION="$1"
else
    # Argument entered by the user.
    echo ""
    echo "To proceed, enter the name of the Bundle to install."
    echo "Press Return to perform a standard installation."
    echo ""
    echo -n "Name: "
    read 'SELECTION'
    if [[ -z "$SELECTION" ]]; then
        # Default argument.
        SELECTION="Chrome CommandLineTools EC2 Firefox Fonts IRC \
        ProjectsFolder SourceTree SublimeText Vagrant Wacom"
    fi
fi

for f in $(echo $SELECTION); do
    echo ""
    echo "$f bundle..."
    curl -L# $SOURCE/$f.install | bash
done

## Invalidate the user time stamp and require passwords again.
sudo -k

echo "The installation was successful."

exit
